## Fichero de configuración para VidTracker

# spring.datasource.url: jdbc:mysql://localhost:33060/vidtracker
# spring.datasource.url: jdbc:h2:~/h2db/vid
#spring.datasource.username: vidtracker
#spring.datasource.password: rastrea

#spring.jpa.properties.javax.persistence.schema-generation.database.action: none

spring.datasource.url: jdbc:h2:~/h2db/vidtracker;AUTO_SERVER=TRUE
spring.data.jpa.repositories.bootstrap-mode: default

spring.jpa.show-sql: true
spring.jpa.generate-ddl: true
spring.jpa.defer-datasource-initialization: true
spring.sql.init.mode: always
spring.jpa.properties.javax.persistence.schema-generation.database.action: drop-and-create

spring.security.user.name: admin
spring.security.user.password: admin

spring.mvc.view.prefix: /WEB-INF/
spring.mvc.view.suffix: .jsp